apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
spec:
  accessModes:
    - {{ .Values.storage.accessMode }}
  storageClassName: {{ .Values.storage.className }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  # Astuce : Si tu veux être sûr à 100% qu'il prenne CELUI créé par Helm
  volumeName: {{ .Release.Name }}-pv
